#!/usr/bin/env python3
"""
clear_incident_data.py
----------------------
Deletes all incident, evidence, and related data from cctv_db while
preserving users, cameras, sensitivity settings, device tokens, and
model versions.

Tables cleared:
  sos_alerts, evidence_blockchain, audit_logs, evidence_shares,
  notifications, evidence, incidents, detection_logs

Run from the backend/ directory:
  python clear_incident_data.py
"""

import sys

try:
    import psycopg2
except ImportError:
    print("[ERROR] psycopg2 is not installed. Run: pip install psycopg2-binary")
    sys.exit(1)

# ──────────────────────────────────────────────────────────────
# Database connection – matches the app's runtime config
# ──────────────────────────────────────────────────────────────
DB_DSN = "postgresql://postgres:admin123@localhost:5432/cctv_db"

# Tables to wipe (order doesn't matter – we use CASCADE, but keeping
# children-first makes the intent explicit)
TABLES_TO_CLEAR = [
    "sos_alerts",
    "evidence_blockchain",
    "audit_logs",
    "evidence_shares",
    "notifications",
    "evidence",
    "incidents",
    "detection_logs",
]


def row_count(cur, table: str) -> int:
    cur.execute(f"SELECT COUNT(*) FROM {table}")          # table names are literals
    return cur.fetchone()[0]


def print_counts(cur, tables, label: str):
    print(f"\n{label}")
    for tbl in tables:
        try:
            n = row_count(cur, tbl)
            print(f"  {tbl:<32} {n:>7} rows")
        except Exception as exc:
            print(f"  {tbl:<32}   ERROR: {exc}")
            cur.connection.rollback()


def main():
    sep = "=" * 62
    print(sep)
    print("  AI-CCTV  —  Incident & Evidence Data Cleanup")
    print(sep)

    safe_dsn = DB_DSN.replace("admin123", "***")
    print(f"\nDatabase : {safe_dsn}")

    # ── Connect ──────────────────────────────────────────────
    try:
        conn = psycopg2.connect(DB_DSN)
        conn.autocommit = False
        cur = conn.cursor()
        print("Status   : Connected\n")
    except Exception as exc:
        print(f"\n[ERROR] Cannot connect to database: {exc}")
        sys.exit(1)

    # ── Show current counts ───────────────────────────────────
    print_counts(cur, TABLES_TO_CLEAR, "Current record counts:")

    # ── Confirmation prompt ───────────────────────────────────
    print()
    print("  This will PERMANENTLY DELETE all incident and evidence data.")
    print("  Preserved: users · cameras · sensitivity_settings ·")
    print("             device_tokens · model_versions")
    print()
    confirm = input("  Type  YES  to proceed (anything else cancels): ").strip()

    if confirm != "YES":
        print("\n[ABORT] No data was changed. Goodbye.")
        cur.close()
        conn.close()
        sys.exit(0)

    # ── Truncate ──────────────────────────────────────────────
    print("\n[INFO] Truncating tables and resetting ID sequences …")
    try:
        tables_sql = ", ".join(TABLES_TO_CLEAR)
        # RESTART IDENTITY resets all serial / SEQUENCE counters for these tables
        # CASCADE ensures FK-dependent rows in any unlisted table are also removed
        cur.execute(
            f"TRUNCATE TABLE {tables_sql} RESTART IDENTITY CASCADE"
        )

        # Reset camera_status performance counters but keep the rows themselves
        cur.execute("""
            UPDATE camera_status
            SET total_incidents = 0,
                total_frames    = 0,
                fps             = 0.0,
                last_frame_time = NULL,
                error_message   = NULL
        """)

        conn.commit()
        print("[OK]   Truncation committed.\n")

    except Exception as exc:
        conn.rollback()
        print(f"\n[ERROR] Truncation failed, transaction rolled back: {exc}")
        cur.close()
        conn.close()
        sys.exit(1)

    # ── Verify ────────────────────────────────────────────────
    print_counts(cur, TABLES_TO_CLEAR, "Post-cleanup record counts:")

    # Quick sanity check
    all_empty = all(row_count(cur, t) == 0 for t in TABLES_TO_CLEAR)

    cur.close()
    conn.close()

    print()
    if all_empty:
        print("[DONE] All incident and evidence data removed.")
        print("       ID sequences reset — new records start from 1.")
        print("       The dashboard will show empty lists until new")
        print("       incidents are generated by the AI worker.")
    else:
        print("[WARN] Some tables still contain rows — check the counts above.")

    print(sep)


if __name__ == "__main__":
    main()
